correcion ngrok

diff --git a/.github/workflows/microservices.yml b/.github/workflows/microservices.yml
--- a/.github/workflows/microservices.yml
+++ b/.github/workflows/microservices.yml
@@ -17,45 +17,42 @@ on:
         type: string
 
 jobs:
-    register-user:
-        runs-on: ubuntu-latest
-    
-        steps:
-          - name: Checkout code
-            uses: actions/checkout@v2
+  register-user:
+    runs-on: ubuntu-latest
 
-          - name: Register User
-            id: register
-            run: |
-                response=$(curl -s -w "%{http_code}" -o response.txt -X POST  https://5965-38-25-25-217.ngrok-free.app/api/v1/register \
-                    -H "Content-Type: application/json" \
-                    -d '{
-                    "username": "${{ github.event.inputs.username }}",
-                    "email": "${{ github.event.inputs.email }}",
-                    "password": "${{ github.event.inputs.password }}"
-                    }')
-                http_code=$(tail -n1 <<< "$response")
-                if [ "$http_code" -ne 200 ]; then
-                    echo "Error en el registro de usuario"
-                    cat response.txt
-                    exit 1
-                fi
-                echo "Usuario registrado exitosamente"
-                cat response.txt
-          
-          - name: Verificar registro
-            if: steps.register.outcome != 'success'
-            run: |
-              echo "Error en el registro de usuario"
-              echo "response: ${{ steps.register.outputs.response }}"
-              exit 1
-          
-          - name: Registro exitoso
-            if: steps.register.outcome == 'success'
-            run: |
-              echo "Usuario registrado exitosamente"
-              echo "response: ${{ steps.register.outputs.response }}"
-        
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-        
+      - name: Register User
+        id: register
+        run: |
+          response=$(curl -s -w "%{http_code}" -o response.txt -X POST https://5965-38-25-25-217.ngrok-free.app/api/v1/users/register \
+            -H "Content-Type: application/json" \
+            -d '{
+              "username": "${{ github.event.inputs.username }}",
+              "email": "${{ github.event.inputs.email }}",
+              "password": "${{ github.event.inputs.password }}"
+            }')
+          http_code=$(tail -n1 <<< "$response")
+          if [ "$http_code" -ne 200 ]; then
+            echo "Error en el registro de usuario"
+            cat response.txt
+            exit 1
+          fi
+          echo "Usuario registrado exitosamente"
+          cat response.txt
+
+      - name: Verificar registro
+        if: steps.register.outcome != 'success'
+        run: |
+          echo "Error en el registro de usuario"
+          echo "response: ${{ steps.register.outputs.response }}"
+          exit 1
+
+      - name: Registro exitoso
+        if: steps.register.outcome == 'success'
+        run: |
+          echo "Usuario registrado exitosamente"
+          echo "response: ${{ steps.register.outputs.response }}"
         
